### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by narqo** [davidae/jm#4]
We've noticed the project doesn't include any explicit licencing.

We find the library very useful for our needs, but without a permissive licence, we are repealed from vendoring it (in general, "[no license][1]" means the project is prohibited from being used as a dependency).

Can we kindly ask to add a licence to the project, and tag a new release?

[1]: https://choosealicense.com/no-permission/

**Comment by davidae** [comment]
Done. New release created too, https://github.com/davidae/jm/releases/tag/v1.2.2
